### ISSUE TITLE
missing find_channel() in pluto.py

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/plutosdr_scripts#6]
channels are hard coded - which isn't going to work on all systems.

Mark reported a problem based on this code.

-Robin

**Comment by tfcollins** [comment]
I left the dac and adc channel indexing still in there, since stream channels should always go 0-N and I think its probably more readable.

**Comment by rgetz** [comment]
You are not guaranteed that things are the same order all the time, or if someone changes a kernel driver, that it will continue to work.

(The sorting updates in libiio breaks this for sure).

**Comment by tfcollins** [comment]
Updated them all.
